packages:
    # all packages in subdirs of packages/ and components/
    - "packages/*"
    # exclude packages that are inside test/ directories
    #- '!**/test/**'
    # exclude test-app if there is any
    # - "!packages/test-app"
